// Command generate regenerates internal/npcfactions/npcfactions.go from
// CCP's SDE npcCorporations.jsonl file.
//
// It exists because ESI cannot supply the faction of an arbitrary NPC
// corporation: GET /corporations/{id} returns faction_id only for the four
// faction-warfare militia corporations, and omits it for every other NPC
// corporation (including Rens's owner, Brutor Tribe 1000049). The SDE's
// npcCorporations.jsonl carries the factionID field the broker-fee formula
// needs, so that mapping is vendored here instead of fetched at runtime.
//
// Usage:
//
//	go run ./internal/npcfactions/generate /path/to/npcCorporations.jsonl
//
// The SDE JSON Lines dump is published at
// https://developers.eveonline.com/static-data/ (the `*-jsonl.zip`
// download); extracting npcCorporations.jsonl from that archive is the
// caller's job. The generator writes npcfactions.go beside itself and is
// deterministic, so regenerating against a new SDE build produces a clean
// diff.
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"sort"
)

// corp is the subset of an npcCorporations.jsonl record the mapping needs.
type corp struct {
	Key       int `json:"_key"`
	FactionID int `json:"factionID"`
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: go run ./internal/npcfactions/generate <path to npcCorporations.jsonl>")
		os.Exit(2)
	}
	in := os.Args[1]

	f, err := os.Open(in)
	if err != nil {
		fmt.Fprintf(os.Stderr, "opening %s: %v\n", in, err)
		os.Exit(1)
	}
	defer f.Close()

	mapping := map[int]int{}
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 16*1024*1024)
	for scanner.Scan() {
		var c corp
		if err := json.Unmarshal(scanner.Bytes(), &c); err != nil {
			fmt.Fprintf(os.Stderr, "decoding record: %v\n", err)
			os.Exit(1)
		}
		if c.Key == 0 || c.FactionID == 0 {
			continue // internal corp with no faction (or a malformed key)
		}
		mapping[c.Key] = c.FactionID
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "reading %s: %v\n", in, err)
		os.Exit(1)
	}

	ids := make([]int, 0, len(mapping))
	for id := range mapping {
		ids = append(ids, id)
	}
	sort.Ints(ids)

	// Run from the repository root; the output lands in the package.
	out, err := os.Create("internal/npcfactions/npcfactions.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "creating npcfactions.go: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	w := bufio.NewWriter(out)
	fmt.Fprint(w, header)
	for _, id := range ids {
		fmt.Fprintf(w, "\t%d: %d,\n", id, mapping[id])
	}
	fmt.Fprint(w, footer)
	if err := w.Flush(); err != nil {
		fmt.Fprintf(os.Stderr, "writing npcfactions.go: %v\n", err)
		os.Exit(1)
	}
}

const header = `// Code generated by go run ./internal/npcfactions/generate from the SDE
// npcCorporations.jsonl; DO NOT EDIT.

// Package npcfactions is a vendored, generated map from an NPC
// corporation's id to the faction that owns it. ESI's
// GET /corporations/{id} omits faction_id for every NPC corporation except
// the four faction-warfare militia corps, so the station owner's faction --
// required for the broker-fee standings term (docs/spec/v2.md §9) -- must
// come from the SDE. Vendoring the mapping keeps the fee path free of any
// runtime SDE dependency.
package npcfactions

// Faction returns the faction id that owns corpID. ok is false for a
// corporation absent from the SDE (e.g. a player corporation), or an NPC
// corporation the SDE gives no factionID (Polaris and a handful of other
// internal corps), in which case no faction standing applies.
func Faction(corpID int) (faction int, ok bool) {
	faction, ok = corpFaction[corpID]
	return faction, ok
}

// corpFaction is generated from the SDE npcCorporations.jsonl factionID
// field, sorted by corporation id.
var corpFaction = map[int]int{
`

const footer = "}\n"
