#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# shellcheck disable=SC2034  # palette colours; some are used only by later stages

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
    BOLD=$(tput bold)
    DIM=$(tput dim)
    RESET=$(tput sgr0)
    BLUE=$(tput setaf 4)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    RED=$(tput setaf 1)
else
    BOLD=""
    DIM=""
    RESET=""
    BLUE=""
    GREEN=""
    YELLOW=""
    RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
    [[ -t 1 ]] || return 0
    if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
    _clear
    printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
    printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
    printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
    printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
    printf '  later, since it remembers values already saved.%s\n' "$RESET"
    pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
    _clear
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
        "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
    local url="$1"
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
    {
        if command -v wslview   >/dev/null 2>&1; then
                                                      wslview "$url"
        elif command -v explorer.exe >/dev/null 2>&1; then
                                                       explorer.exe "$url"
        elif command -v xdg-open >/dev/null 2>&1; then
                                                      xdg-open "$url"
        elif command -v open    >/dev/null 2>&1; then
                                                      open "$url"
        else warn "couldn't open a browser; visit it manually: $url"; fi
    } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
    printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
    read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
    local reply=""
    printf '  %s? %s [y/N] ' "$YELLOW" "$1"
    read -r reply || true
    [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
    [[ -f "$ENV_FILE" ]] || return 1
    local line
              line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
    printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -r input || true
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -rs input || true
    printf '\n'
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
    local key="$1" value="$2" tmp
    touch "$ENV_FILE"
    tmp=$(mktemp)
    grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
    printf '%s=%s\n' "$key" "$value" >>"$tmp"
    mv "$tmp" "$ENV_FILE"
    WRITTEN_ENV+=("$key")
    printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
            WRITTEN_SECRET+=("$name")
            printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
    warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
            printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub variable $name")
    warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
    _clear
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
    ((${#WRITTEN_ENV[@]}))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
    ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
    if ((${#SKIPPED[@]})); then
        printf '\n'
                 warn "still to do by hand:"
        for s in "${SKIPPED[@]}"; do note "  - $s"; done
    fi
    printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/eve-trader"
ENV_FILE="${ENV_FILE:-$CONFIG_DIR/sso.env}"
CRED_FILE="$CONFIG_DIR/credentials.json"
WORKDIR="$(mktemp -d)"
                        trap 'rm -rf "$WORKDIR"' EXIT
HELPER="$WORKDIR/sso.py"
CODE_FILE="$WORKDIR/code.txt"

cat >"$HELPER"  <<'PY'
import sys, os, json, base64, hashlib, secrets, urllib.parse, urllib.request, http.server

AUTH = "https://login.eveonline.com/v2/oauth/authorize"
TOKEN = "https://login.eveonline.com/v2/oauth/token"
SCOPES = "esi-skills.read_skills.v1 esi-characters.read_standings.v1"
SKILL_NAMES = {3443: "Trade", 3444: "Retail", 3446: "Broker Relations", 3447: "Visibility",
               16594: "Procurement", 16595: "Daytrading", 16596: "Wholesale",
               16597: "Advanced Broker Relations", 16598: "Marketing", 16622: "Accounting",
               18580: "Tycoon"}

def pkce():
    # CCP's own non-RFC-7636 byte handling: the verifier is the base64url of 32
    # random bytes (44 chars, keeps '='); the challenge is its unpadded sha256.
    verifier = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()
    challenge = base64.urlsafe_b64encode(hashlib.sha256(verifier.encode()).digest()).decode().rstrip("=")
    print(verifier, challenge, secrets.token_urlsafe(16))

def authorize(client_id, redirect_uri, state, challenge):
    q = urllib.parse.urlencode({"response_type": "code", "client_id": client_id,
        "redirect_uri": redirect_uri, "scope": SCOPES, "state": state,
        "code_challenge": challenge, "code_challenge_method": "S256"})
    print(AUTH + "?" + q)

def port(redirect_uri):
    print(urllib.parse.urlparse(redirect_uri).port or 80)

def post(data):
    body = urllib.parse.urlencode(data).encode()
    req = urllib.request.Request(TOKEN, data=body,
        headers={"Content-Type": "application/x-www-form-urlencoded"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)

def exchange(client_id, code, verifier):
    print(json.dumps(post({"grant_type": "authorization_code", "code": code,
        "code_verifier": verifier, "client_id": client_id})))

def refresh(client_id, refresh_token):
    print(json.dumps(post({"grant_type": "refresh_token", "refresh_token": refresh_token,
        "client_id": client_id})))

def get(url, token):
    req = urllib.request.Request(url, headers={"Authorization": "Bearer " + token})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)

def verify(access_token):
    p = access_token.split(".")[1]; p += "=" * (-len(p) % 4)
    sub = json.loads(base64.urlsafe_b64decode(p))["sub"]
    cid = sub.split(":")[-1]
    skills = {s["skill_id"]: s["active_skill_level"]
              for s in get(f"https://esi.evetech.net/latest/characters/{cid}/skills/", access_token)["skills"]}
    out = {"character_id": cid, "sub": sub,
           "skills": {SKILL_NAMES[k]: v for k, v in skills.items() if k in SKILL_NAMES}}
    try:
        st = get(f"https://esi.evetech.net/latest/characters/{cid}/standings/", access_token)
        out["standings_count"] = len(st)
    except Exception as e:
        out["standings_error"] = str(e)
    print(json.dumps(out, indent=1))

def capture(p, outfile):
    class H(http.server.BaseHTTPRequestHandler):
        def do_GET(self):
            q = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            with open(outfile, "w") as f:
                f.write(q.get("code", [""])[0] + "\n" + q.get("state", [""])[0] + "\n")
            self.send_response(200); self.send_header("Content-Type", "text/html"); self.end_headers()
            self.wfile.write(b"<h2>eve-trader: authorization received. You can close this tab.</h2>")
        def log_message(self, *a): pass
    srv = http.server.HTTPServer(("127.0.0.1", int(p)), H)
    srv.socket.settimeout(300)
    try: srv.handle_request()
    except Exception: pass

{"pkce": lambda: pkce(), "authorize": lambda: authorize(*sys.argv[2:]),
 "port": lambda: port(*sys.argv[2:]), "exchange": lambda: exchange(*sys.argv[2:]),
 "refresh": lambda: refresh(*sys.argv[2:]), "verify": lambda: verify(*sys.argv[2:]),
 "capture": lambda: capture(*sys.argv[2:])}[sys.argv[1]]()
PY

banner "eve-trader · EVE SSO setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Register the ESI application"
say "We'll create an application in the EVE developer portal and copy its credentials."
open_url "https://developers.eveonline.com/"
step "Sign in, then open Applications → Create New Application."
step "Name it 'eve-trader'; Connection type: Authentication Only (native / desktop)."
step "For Callback URL, enter exactly (fixed host, fixed port, no trailing slash):"
say "    http://127.0.0.1:8000/callback"
note "EVE SSO requires redirect_uri to match a registered callback exactly."
note "CCP documents only 'localhost'; 127.0.0.1 is inferred to work — that is one thing this run proves."
step "Add scopes: esi-skills.read_skills.v1 and esi-characters.read_standings.v1."
step "Save, then copy the Client ID and the Secret Key from the app page."
ask EVE_CLIENT_ID "Paste the Client ID:"
ask_secret EVE_CLIENT_SECRET "Paste the Secret Key (PKCE does not send it; kept for completeness):"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Confirm the redirect URI"
say "The wizard listens on the redirect URI you registered. It must match exactly."
ask EVE_REDIRECT_URI "Redirect URI you registered:"
[[ -n "$EVE_REDIRECT_URI" ]] || EVE_REDIRECT_URI="http://127.0.0.1:8000/callback"
REDIRECT_PORT=$(python3 "$HELPER" port "$EVE_REDIRECT_URI")
note "listening on 127.0.0.1:$REDIRECT_PORT/callback"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Authorize this character"
say "We'll open the EVE SSO consent page, then catch the code on a local listener."
read -r VERIFIER CHALLENGE STATE < <(python3 "$HELPER" pkce)
AUTH_URL=$(python3 "$HELPER" authorize "$EVE_CLIENT_ID" "$EVE_REDIRECT_URI" "$STATE" "$CHALLENGE")
python3 "$HELPER" capture "$REDIRECT_PORT" "$CODE_FILE" &
CAP_PID=$!
sleep 1
open_url "$AUTH_URL"
say "Approve the scopes in the browser. Waiting for the callback (up to 5 min)…"
for _ in $(seq 1 300); do
                          [[ -s "$CODE_FILE" ]] && break
                                                          sleep 1
done
kill "$CAP_PID" 2>/dev/null || true
CODE=$(sed -n 1p "$CODE_FILE" 2>/dev/null || true)
GOT_STATE=$(sed -n 2p "$CODE_FILE" 2>/dev/null || true)
if [[ -z "$CODE" ]]; then
    warn "No authorization code captured. Most likely the redirect URI did not match."
    warn "If the portal rejected 127.0.0.1, register http://localhost:8000/callback and re-run."
    exit 1
fi
[[ "$GOT_STATE" == "$STATE" ]] || {
                                    warn "state mismatch — aborting (possible CSRF)."
                                                                                         exit 1
}
say "Captured the authorization code."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Exchange the code for tokens"
say "Trading the one-time code for an access token (20 min) and a refresh token (long-lived)."
TOKENS=$(python3 "$HELPER" exchange "$EVE_CLIENT_ID" "$CODE" "$VERIFIER")
ACCESS_TOKEN=$(printf '%s' "$TOKENS" | python3 -c 'import sys,json;print(json.load(sys.stdin)["access_token"])')
REFRESH_TOKEN=$(printf '%s' "$TOKENS" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("refresh_token",""))')
[[ -n "$ACCESS_TOKEN" ]] || {
                              warn "no access token returned: $TOKENS"
                                                                        exit 1
}
say "Got an access token and a refresh token."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify the scopes actually work"
say "Decoding the JWT and calling the two scoped routes to prove the round-trip."
python3 "$HELPER" verify "$ACCESS_TOKEN"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Store the credentials"
say "Non-secrets go to sso.env; the refresh token and secret go to a 0600 file."
mkdir -p "$CONFIG_DIR"
                        chmod 700 "$CONFIG_DIR"
python3 - "$CRED_FILE" "$EVE_CLIENT_ID" "$EVE_CLIENT_SECRET" "$EVE_REDIRECT_URI" "$REFRESH_TOKEN" <<'PY'
import json, sys, os
path, cid, csec, redir, rt = sys.argv[1:6]
json.dump({"client_id": cid, "client_secret": csec or None,
           "redirect_uri": redir, "refresh_token": rt}, open(path, "w"), indent=1)
os.chmod(path, 0o600)
PY
write_env EVE_CLIENT_ID "$EVE_CLIENT_ID"
write_env EVE_REDIRECT_URI "$EVE_REDIRECT_URI"
say "refresh token stored (600) at $CRED_FILE"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Prove a refresh works"
say "Minting a fresh access token from the stored refresh token — the long-lived path."
NEWTOKENS=$(python3 "$HELPER" refresh "$EVE_CLIENT_ID" "$REFRESH_TOKEN")
NEW_ACCESS=$(printf '%s' "$NEWTOKENS" | python3 -c 'import sys,json;print(json.load(sys.stdin).get("access_token",""))')
[[ -n "$NEW_ACCESS" ]] || {
                            warn "refresh failed: $NEWTOKENS"
                                                               exit 1
}
ROTATED=$(printf '%s' "$NEWTOKENS" | python3 -c 'import sys,json;print("yes" if json.load(sys.stdin).get("refresh_token") else "no")')
say "Refresh succeeded. Token rotated in response: $ROTATED (always persist the returned one)."

finish
note "client id  → $ENV_FILE (EVE_CLIENT_ID)"
note "token+secret → $CRED_FILE (chmod 600, never in the repo)"
