#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
    BOLD=$(tput bold)
    DIM=$(tput dim)
    RESET=$(tput sgr0)
    BLUE=$(tput setaf 4)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    # shellcheck disable=SC2034 # part of the palette, not every wizard's stages use every color
    RED=$(tput setaf 1)
else
    BOLD=""
    DIM=""
    RESET=""
    BLUE=""
    GREEN=""
    YELLOW=""
    # shellcheck disable=SC2034
    RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
    [[ -t 1 ]] || return 0
    if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
    _clear
    printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
    printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
    printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
    printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
    printf '  later, since it remembers values already saved.%s\n' "$RESET"
    pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
    _clear
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
        "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
    local url="$1"
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
    {
        if command -v wslview >/dev/null 2>&1; then
            wslview "$url"
        elif command -v explorer.exe >/dev/null 2>&1; then
            explorer.exe "$url"
        elif command -v xdg-open >/dev/null 2>&1; then
            xdg-open "$url"
        elif command -v open >/dev/null 2>&1; then
            open "$url"
        else warn "couldn't open a browser; visit it manually: $url"; fi
    } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
    printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
    read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
    local reply=""
    printf '  %s? %s [y/N] ' "$YELLOW" "$1"
    read -r reply || true
    [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
    [[ -f "$ENV_FILE" ]] || return 1
    local line
    line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
    printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -r input || true
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -rs input || true
    printf '\n'
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
    local key="$1" value="$2" tmp
    touch "$ENV_FILE"
    tmp=$(mktemp)
    grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
    printf '%s=%s\n' "$key" "$value" >>"$tmp"
    mv "$tmp" "$ENV_FILE"
    WRITTEN_ENV+=("$key")
    printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
            WRITTEN_SECRET+=("$name")
            printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
    warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
            printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub variable $name")
    warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
    _clear
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
    ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
    ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
    if ((${#SKIPPED[@]})); then
        printf '\n'
        warn "still to do by hand:"
        for s in "${SKIPPED[@]}"; do note "  - $s"; done
    fi
    printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# This wizard finishes eve-trader issue #20 (Full CI/CD + deployment
# automation): the repo-config half (release-please.yml, release.yml,
# .goreleaser.yaml, Dockerfile, dependabot.yml) is already committed. What's
# left needs a human: real GitHub App credentials and SSH access to the GCP
# VM this session doesn't have.
#
# Secrets captured here for the VM (ESI Client ID/Secret, Discord webhook,
# the ghcr.io pull PAT) are deliberately NOT written to ENV_FILE -- unlike
# STRIPE_SECRET_KEY in the template example, these are live production
# credentials for infrastructure this script writes directly to the VM over
# SSH; persisting a second copy in a local .env would just be one more place
# for them to leak from. Only RELEASE_PLEASE_APP_PRIVATE_KEY, which CI
# itself needs as a GitHub secret, goes through set_secret.

TOTAL_STAGES=9

banner "eve-trader: finish CI/CD + deployment automation (#20)"

# gcp_ssh CMD runs CMD on the VM non-interactively via gcloud. Defined here
# (not in the library) since it's specific to this wizard's target host.
gcp_ssh() {
    gcloud compute ssh "$GCP_INSTANCE" --project "$GCP_PROJECT" --zone "$GCP_ZONE" --command "$1"
}

# ── Stage 1: which VM ───────────────────────────────────────────────────────
stage "Which VM"
say "Everything from here on runs against the GCP VM via 'gcloud compute ssh'."
ask GCP_PROJECT "GCP project ID:"
ask GCP_ZONE "GCP zone (e.g. us-central1-a):"
ask GCP_INSTANCE "VM instance name [Enter for eve-trader-vm]:"
GCP_INSTANCE="${GCP_INSTANCE:-eve-trader-vm}"
say "Checking connectivity..."
if gcp_ssh "echo ok" >/dev/null 2>&1; then
    printf '  %s✓%s connected to %s\n' "$GREEN" "$RESET" "$GCP_INSTANCE"
else
    warn "couldn't reach $GCP_INSTANCE with those details -- fix and re-run before continuing"
    exit 1
fi

# ── Stage 2: release-please App repo access ─────────────────────────────────
stage "Grant the release-please App access to eve-trader"
say "eve-pi-optimizer already has a GitHub App set up for release-please"
say "(client ID Iv23lijnZgs6R7WhJM7P, already recorded as this repo's"
say "RELEASE_PLEASE_APP_CLIENT_ID variable). It just needs access to this repo too."
open_url "https://github.com/settings/installations"
step "Find the App (match by client ID Iv23lijnZgs6R7WhJM7P on its settings page)."
step "Click Configure. Under Repository access, add eve-trader"
step "(skip if it's already set to 'All repositories')."
confirm "Confirmed eve-trader has access?" || warn "come back to this before merging a release-please PR"

# ── Stage 3: release-please App private key -> GitHub secret ───────────────
stage "release-please App private key"
say "This is the one secret CI actually needs -- it goes to a GitHub secret,"
say "not the VM."
open_url "https://github.com/settings/apps"
step "Open the App matching client ID Iv23lijnZgs6R7WhJM7P."
step "Scroll to 'Private keys' -> 'Generate a private key' (downloads a .pem;"
step "existing keys, if any, keep working)."
ask RELEASE_PLEASE_KEY_PATH "Path to the downloaded .pem file:"
if [[ -f "$RELEASE_PLEASE_KEY_PATH" ]]; then
    set_secret RELEASE_PLEASE_APP_PRIVATE_KEY "$(cat "$RELEASE_PLEASE_KEY_PATH")"
    note "you can delete the downloaded .pem now; it's stored as the GitHub secret"
else
    warn "no file at that path -- skipped. Set it later: gh secret set RELEASE_PLEASE_APP_PRIVATE_KEY < path/to/key.pem"
    SKIPPED+=("GitHub secret RELEASE_PLEASE_APP_PRIVATE_KEY")
fi

# ── Stage 4: ghcr.io pull access on the VM ──────────────────────────────────
stage "ghcr.io pull access for the VM"
say "eve-trader is a private repo, so its ghcr.io package is private too --"
say "the VM needs its own credential to pull (it isn't a GitHub Actions"
say "runner, so it can't use GITHUB_TOKEN)."
open_url "https://github.com/settings/tokens/new"
step "Name it something like 'eve-trader-vm-ghcr-pull'."
step "Scope: check only 'read:packages'. Generate, then copy the token."
ask_secret GHCR_PAT "Paste the token:"
GH_USERNAME="$(gh api user --jq .login 2>/dev/null || true)"
if [[ -z "$GH_USERNAME" ]]; then
    ask GH_USERNAME "Your GitHub username:"
fi
if printf '%s' "$GHCR_PAT" | gcp_ssh "docker login ghcr.io -u '$GH_USERNAME' --password-stdin"; then
    printf '  %s✓%s docker login succeeded on the VM\n' "$GREEN" "$RESET"
else
    warn "docker login failed on the VM -- Watchtower won't be able to pull until this works"
fi

# ── Stage 5: shared Docker network ──────────────────────────────────────────
stage "Shared Docker network"
say "Caddy already runs on eve-trader-net per the spec; make sure it exists"
say "(idempotent -- fine if it's already there)."
gcp_ssh "docker network inspect eve-trader-net >/dev/null 2>&1 || docker network create eve-trader-net"
printf '  %s✓%s eve-trader-net is present\n' "$GREEN" "$RESET"

# ── Stage 6: app secrets env file on the VM ─────────────────────────────────
stage "App secrets on the VM"
say "These go into a chmod-600 env file on the VM (~/eve-trader.env), per the"
say "spec -- not GitHub secrets, since the container reads them directly."
say "The ESI Client ID/Secret are from the developer application registered"
say "at https://developers.eveonline.com/applications (already done, per the spec)."
ask_secret ESI_CLIENT_ID "ESI Client ID:"
ask_secret ESI_CLIENT_SECRET "ESI Client Secret:"
ask_secret DISCORD_WEBHOOK_URL "Discord webhook URL [Enter to skip Discord alerts for now]:"
{
    printf 'EVE_TRADER_ESI_CLIENT_ID=%s\n' "$ESI_CLIENT_ID"
    printf 'EVE_TRADER_ESI_CLIENT_SECRET=%s\n' "$ESI_CLIENT_SECRET"
    [[ -n "$DISCORD_WEBHOOK_URL" ]] && printf 'EVE_TRADER_DISCORD_WEBHOOK_URL=%s\n' "$DISCORD_WEBHOOK_URL"
} | gcp_ssh "cat > ~/eve-trader.env && chmod 600 ~/eve-trader.env"
printf '  %s✓%s wrote ~/eve-trader.env on the VM (mode 600)\n' "$GREEN" "$RESET"

# ── Stage 7: first-time app container ───────────────────────────────────────
stage "First deploy of the eve-trader container"
say "No host port is published -- Caddy reverse-proxies to it over"
say "eve-trader-net by container name (eve-trader:8080)."
gcp_ssh "mkdir -p ~/eve-trader-data"
gcp_ssh "docker pull ghcr.io/mgoodness/eve-trader:stable"
gcp_ssh "docker rm -f eve-trader >/dev/null 2>&1 || true"
gcp_ssh "docker run -d --name eve-trader --restart=always --network eve-trader-net --env-file ~/eve-trader.env -e EVE_TRADER_DB_PATH=/data/eve-trader.db -v ~/eve-trader-data:/data ghcr.io/mgoodness/eve-trader:stable"
gcp_ssh "docker ps --filter name=eve-trader --format '{{.Names}}: {{.Status}}'"
warn "I can't see the VM's current Caddyfile -- verify it proxies"
warn "eve-trader.opsgoodness.net to eve-trader:8080, and reload Caddy if you"
warn "change it."
confirm "Caddy routing verified/updated?" || SKIPPED+=("verify Caddy proxies to eve-trader:8080")

# ── Stage 8: Watchtower ─────────────────────────────────────────────────────
stage "Watchtower"
say "Scoped to just the eve-trader container (not Caddy or anything else on"
say "the VM), polling every 5 minutes."
gcp_ssh "docker rm -f watchtower >/dev/null 2>&1 || true"
# Single-quoted deliberately: $HOME must expand on the VM (where the
# docker/login-action-equivalent credential file actually lives), not on
# this machine -- shellcheck's SC2016 note doesn't apply here.
# shellcheck disable=SC2016
gcp_ssh 'docker run -d --name watchtower --restart=always --network eve-trader-net -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/.docker/config.json:/config.json:ro containrrr/watchtower --interval 300 eve-trader'
gcp_ssh "docker ps --filter name=watchtower --format '{{.Names}}: {{.Status}}'"

# ── Stage 9: end-to-end proof ────────────────────────────────────────────────
stage "Prove it end-to-end"
say "This is the AC's own proof, so do it for real once, now that everything"
say "above is wired up:"
step "Push a Conventional Commit (feat:/fix:) to main, or merge the next"
step "release-please PR if one's already open."
step "Watch release.yml run in GitHub Actions -- it should build and push"
step "ghcr.io/mgoodness/eve-trader:<version> and :stable."
step "Watch Watchtower notice and redeploy (within ~5 min):"
note "    gcloud compute ssh $GCP_INSTANCE --project $GCP_PROJECT --zone $GCP_ZONE --command 'docker logs -f watchtower'"
confirm "Confirmed a fresh image landed on ghcr.io and the VM redeployed automatically?"

finish
