#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
    BOLD=$(tput bold)
    DIM=$(tput dim)
    RESET=$(tput sgr0)
    BLUE=$(tput setaf 4)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    # shellcheck disable=SC2034 # part of the palette, not every wizard's stages use every color
    RED=$(tput setaf 1)
else
    BOLD=""
    DIM=""
    RESET=""
    BLUE=""
    GREEN=""
    YELLOW=""
    # shellcheck disable=SC2034
    RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
    [[ -t 1 ]] || return 0
    if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
    _clear
    printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
    printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
    printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
    printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
    printf '  later, since it remembers values already saved.%s\n' "$RESET"
    pause "Ready to start?"
}

stage() {
    _clear
    _STAGE_INDEX=$((_STAGE_INDEX + 1))
    printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
        "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
    local url="$1"
    printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
    {
        if command -v wslview   >/dev/null 2>&1; then
                                                      wslview "$url"
        elif command -v explorer.exe >/dev/null 2>&1; then
                                                       explorer.exe "$url"
        elif command -v xdg-open >/dev/null 2>&1; then
                                                      xdg-open "$url"
        elif command -v open    >/dev/null 2>&1; then
                                                      open "$url"
        else warn "couldn't open a browser; visit it manually: $url"; fi
    } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
    printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
    read -r _ || true
}

confirm() {
    local reply=""
    printf '  %s? %s [y/N] ' "$YELLOW" "$1"
    read -r reply || true
    [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
    [[ -f "$ENV_FILE" ]] || return 1
    local line
              line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
    printf '%s' "${line#*=}"
}

ask() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -r input || true
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

ask_secret() {
    local key="$1" prompt="$2" current input
    current=$(_existing "$key" || true)
    if [[ -n "$current" ]]; then
        printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    else
        printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
    fi
    read -rs input || true
    printf '\n'
    [[ -z "$input" && -n "$current" ]] && input="$current"
    printf -v "$key" '%s' "$input"
}

write_env() {
    local key="$1" value="$2" tmp
    touch "$ENV_FILE"
    tmp=$(mktemp)
    grep -vE "^${key}=" "$ENV_FILE" >"$tmp" || true
    printf '%s=%s\n' "$key" "$value" >>"$tmp"
    mv "$tmp" "$ENV_FILE"
    WRITTEN_ENV+=("$key")
    printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
            WRITTEN_SECRET+=("$name")
            printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
    warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
    local name="$1" value="$2"
    if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
        if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
            printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
            return
        fi
    fi
    SKIPPED+=("GitHub variable $name")
    warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
    _clear
    printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
    ((${#WRITTEN_ENV[@]}))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
    ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
    if ((${#SKIPPED[@]})); then
        printf '\n'
                 warn "still to do by hand:"
        for s in "${SKIPPED[@]}"; do note "  - $s"; done
    fi
    printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Adapted from issue #63's agent brief. Uses `gcloud compute ssh` (matching
# scripts/setup-cicd.sh's gcp_ssh convention) instead of a plain ssh
# alias/host, since the eve-trader VM is reached via gcloud, not a
# directly-addressable SSH host.

TOTAL_STAGES=6

banner "Watchtower instant-deploy webhook setup (#63)"

# gcp_ssh CMD runs CMD on the VM non-interactively via gcloud -- same
# helper shape as scripts/setup-cicd.sh.
gcp_ssh() {
    gcloud compute ssh "$GCP_INSTANCE" --project "$GCP_PROJECT" --zone "$GCP_ZONE" --command "$1"
}

# ── Stage 1: which VM ───────────────────────────────────────────────────────
stage "Which VM"
say "Everything from here on runs against the GCP VM via 'gcloud compute ssh'."
ask GCP_PROJECT "GCP project ID:"
ask GCP_ZONE "GCP zone (e.g. us-central1-a):"
ask GCP_INSTANCE "VM instance name [Enter for eve-trader-vm]:"
GCP_INSTANCE="${GCP_INSTANCE:-eve-trader-vm}"
write_env GCP_PROJECT "$GCP_PROJECT"
write_env GCP_ZONE "$GCP_ZONE"
write_env GCP_INSTANCE "$GCP_INSTANCE"
say "Checking connectivity..."
if gcp_ssh "echo ok" >/dev/null 2>&1; then
    printf '  %s✓%s connected to %s\n' "$GREEN" "$RESET" "$GCP_INSTANCE"
else
    warn "couldn't reach $GCP_INSTANCE with those details -- fix and re-run before continuing"
    exit 1
fi

# ── Stage 2: inspect the current Watchtower container ────────────────────────
stage "Inspect the current Watchtower container"
say "This isn't checked into the repo yet (see #67), so we read the live host config directly."
say "Current container:"
gcp_ssh 'docker ps --filter name=watchtower --format "{{.Names}}: {{.Status}}  {{.Command}}"' || true
say "Full config (image, env, mounts, network, restart policy):"
# {{$k}}/{{$v}} below are Go template range variables for `docker
# inspect --format`, not shell variables -- single quotes correctly
# keep them from expanding anywhere.
# shellcheck disable=SC2016
gcp_ssh 'docker inspect watchtower --format "image:  {{.Config.Image}}
restart: {{.HostConfig.RestartPolicy.Name}}
network: {{range \$k, \$v := .NetworkSettings.Networks}}{{\$k}} {{end}}
env:     {{range .Config.Env}}{{.}} {{end}}
mounts:  {{range .Mounts}}{{.Source}} -> {{.Destination}} {{end}}
cmd:     {{.Config.Cmd}}"' || warn "couldn't inspect a 'watchtower' container -- is the name different, or is it run via docker compose instead of a bare 'docker run'? If so, the exact re-run command in the next stage won't match -- find its compose file instead: gcloud compute ssh $GCP_INSTANCE --project $GCP_PROJECT --zone $GCP_ZONE --command 'find / -maxdepth 5 -iname docker-compose.yml 2>/dev/null'"
note "If that output matches containrrr/watchtower run with --network eve-trader-net, -v /var/run/docker.sock:/var/run/docker.sock, -v \$HOME/.docker/config.json:/config.json:ro, and --interval 300 eve-trader (the invocation scripts/setup-cicd.sh originally used), the next stage's replacement command will just work as printed."
pause "Press Enter to continue."

# ── Stage 3: enable Watchtower's HTTP API ────────────────────────────────────
stage "Enable Watchtower's HTTP API"
say "Generate a long random bearer token that will authorize the webhook call."
if command -v openssl >/dev/null 2>&1; then
    WATCHTOWER_WEBHOOK_TOKEN="$(openssl rand -hex 32)"
    note "generated: $WATCHTOWER_WEBHOOK_TOKEN"
else
    warn "openssl not found locally -- run 'openssl rand -hex 32' on any machine that has it"
    ask_secret WATCHTOWER_WEBHOOK_TOKEN "Paste a token to use:"
fi
say "Run this on the host (recreates the container with the same image/mounts/network as before, plus the HTTP API enabled on port 8080 -- adjust first if stage 2's inspect output didn't match the assumed invocation). The -p 127.0.0.1:8080:8080 keeps it off the public internet, but the real isolation is Docker's network: Caddy reaches this container by name (watchtower:8080) over eve-trader-net, not via localhost or the published host port -- see stage 4."
cat <<CMD

  gcloud compute ssh $GCP_INSTANCE --project $GCP_PROJECT --zone $GCP_ZONE --command '
    docker rm -f watchtower
    docker run -d --name watchtower --restart=always --network eve-trader-net \\
      -p 127.0.0.1:8080:8080 \\
      -e WATCHTOWER_HTTP_API_UPDATE=true \\
      -e WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_WEBHOOK_TOKEN} \\
      -v /var/run/docker.sock:/var/run/docker.sock \\
      -v \$HOME/.docker/config.json:/config.json:ro \\
      containrrr/watchtower --interval 300 --http-api-metrics eve-trader
  '

CMD
if confirm "Ready to run that now (this wizard will run it for you over gcloud)?"; then
    gcp_ssh "docker rm -f watchtower >/dev/null 2>&1 || true"
    gcp_ssh "docker run -d --name watchtower --restart=always --network eve-trader-net -p 127.0.0.1:8080:8080 -e WATCHTOWER_HTTP_API_UPDATE=true -e WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_WEBHOOK_TOKEN} -v /var/run/docker.sock:/var/run/docker.sock -v \$HOME/.docker/config.json:/config.json:ro containrrr/watchtower --interval 300 --http-api-metrics eve-trader"
    gcp_ssh 'docker ps --filter name=watchtower --format "{{.Names}}: {{.Status}}"'
else
    pause "Run it yourself (command above), then press Enter to continue."
fi

# ── Stage 4: add a Caddy route for the webhook ───────────────────────────────
stage "Add a Caddy route for the webhook"
ask EVE_TRADER_DOMAIN "The domain eve-trader is served on (e.g. eve-trader.example.com):"
write_env EVE_TRADER_DOMAIN "$EVE_TRADER_DOMAIN"
say "Locating the Caddyfile on the host..."
CADDYFILE_PATH="$(gcp_ssh 'sudo find /etc/caddy /opt /home -maxdepth 4 -iname Caddyfile 2>/dev/null | head -n1' 2>/dev/null || true)"
if [[ -n "$CADDYFILE_PATH" ]]; then
    printf '  %s✓%s found: %s\n' "$GREEN" "$RESET" "$CADDYFILE_PATH"
    say "Its current content:"
    gcp_ssh "sudo cat '$CADDYFILE_PATH'" || true
else
    warn "couldn't auto-locate it -- find it yourself:"
    step "gcloud compute ssh $GCP_INSTANCE --project $GCP_PROJECT --zone $GCP_ZONE --command 'sudo find / -maxdepth 6 -iname Caddyfile 2>/dev/null'"
    ask CADDYFILE_PATH "Paste the path once you find it:"
fi
say "Add this inside the existing $EVE_TRADER_DOMAIN site block, BEFORE any catch-all reverse_proxy line (Caddy evaluates same-block directives in file order, first match wins -- a bare, unmatched reverse_proxy placed first will swallow every request before this one ever runs). Use the Watchtower container's name, not localhost -- Caddy and Watchtower are separate containers on the same Docker network (eve-trader-net), and 'localhost' inside Caddy's own container never reaches a sibling container's port. Use handle_path (not a bare reverse_proxy) so the /internal/watchtower-hook prefix is stripped before proxying -- Watchtower's HTTP API only recognizes /v1/update, not the full prefixed path:"
cat <<CMD

    handle_path /internal/watchtower-hook/* {
        reverse_proxy watchtower:8080
    }

CMD
step "gcloud compute ssh $GCP_INSTANCE --project $GCP_PROJECT --zone $GCP_ZONE   # opens a shell"
step "sudo nano $CADDYFILE_PATH   # or vim -- add the block above inside the $EVE_TRADER_DOMAIN block, before any catch-all reverse_proxy line, then save"
pause "Edited and saved? Press Enter to continue."
say "Reload Caddy after saving. If Caddy runs as its own Docker container here (check: docker ps --filter name=caddy), reload via docker exec rather than systemctl -- there's no caddy.service unit in that case:"
if confirm "Ready to reload Caddy now (runs 'docker exec caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile' on the host)?"; then
    gcp_ssh 'docker exec caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile' && printf '  %s✓%s Caddy reloaded\n' "$GREEN" "$RESET"
else
    step "gcloud compute ssh $GCP_INSTANCE --project $GCP_PROJECT --zone $GCP_ZONE --command 'docker exec caddy caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile'"
    note "(or 'sudo systemctl reload caddy' if Caddy runs as a systemd service, not a container, on your host)"
    pause "Caddy reloaded? Press Enter to continue."
fi

# ── Stage 5: verify the webhook works ────────────────────────────────────────
stage "Verify the webhook works"
WATCHTOWER_WEBHOOK_URL="https://${EVE_TRADER_DOMAIN}/internal/watchtower-hook/v1/update"
say "Watchtower's HTTP API update endpoint is: $WATCHTOWER_WEBHOOK_URL"
say "Triggering it and checking Watchtower's logs for an immediate check..."
HTTP_STATUS="$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer ${WATCHTOWER_WEBHOOK_TOKEN}" "$WATCHTOWER_WEBHOOK_URL" || true)"
if [[ "$HTTP_STATUS" == "200" ]]; then
    printf '  %s✓%s webhook responded 200\n' "$GREEN" "$RESET"
else
    warn "webhook responded '$HTTP_STATUS' (want 200) -- check the Caddy route and the container's env vars"
fi
sleep 2
say "Recent Watchtower log lines:"
gcp_ssh 'docker logs --since=15s watchtower' || true
confirm "Did the logs above show an immediate check (not just the usual poll-interval line)?" || warn "don't proceed to CI wiring until this works end to end -- check the Caddy route and the container's env vars"

# ── Stage 6: store the webhook URL and token for GitHub Actions ─────────────
stage "Store the webhook URL and token for GitHub Actions"
say "The follow-up issue (the deploy.yml change) will read these as repo secrets/vars."
write_env WATCHTOWER_WEBHOOK_URL "$WATCHTOWER_WEBHOOK_URL"
write_env WATCHTOWER_WEBHOOK_TOKEN "$WATCHTOWER_WEBHOOK_TOKEN"
set_var WATCHTOWER_WEBHOOK_URL "$WATCHTOWER_WEBHOOK_URL"     # not secret, just an endpoint
set_secret WATCHTOWER_WEBHOOK_TOKEN "$WATCHTOWER_WEBHOOK_TOKEN"

finish
say "Next: the follow-up GitHub issue can now add a curl step to deploy.yml using"
say "the \${{ vars.WATCHTOWER_WEBHOOK_URL }} and \${{ secrets.WATCHTOWER_WEBHOOK_TOKEN }} it just found."
